"""add_moderator_table

Revision ID: 4479c817f503
Revises: 954d08693228
Create Date: 2026-05-24 19:23:06.151023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4479c817f503'
down_revision: Union[str, None] = '954d08693228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator',
    sa.Column('hmac_token', sa.String(length=64), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hmac_token', 'semester', name='uq_moderator_token_semester')
    )
    op.add_column('moderation_log', sa.Column('moderator_hmac_token', sa.String(length=64), nullable=False))
    op.drop_column('moderation_log', 'moderator_hmac')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderation_log', sa.Column('moderator_hmac', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('moderation_log', 'moderator_hmac_token')
    op.drop_table('moderator')
    # ### end Alembic commands ###
