"""initial

Revision ID: 8e6ac8e519f7
Revises: 
Create Date: 2026-05-24 10:40:17.698161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6ac8e519f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_token',
    sa.Column('hmac_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hmac_token')
    )
    op.create_index('ix_session_token_hmac', 'session_token', ['hmac_token'], unique=False)
    op.create_table('topic',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('post',
    sa.Column('hmac_token', sa.String(length=64), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('published', 'flagged', 'under_review', 'removed', 'restored', name='post_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hmac_token'], ['session_token.hmac_token'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flag',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('harassment', 'defamation', 'spam', 'sexual_content', 'threat', 'other', name='flag_reason'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_log',
    sa.Column('action', sa.Enum('remove', 'restore', 'escalate', name='moderation_action'), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('moderator_hmac', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('actioned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petition',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('signature_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'threshold_met', 'closed', name='petition_status'), nullable=False),
    sa.Column('threshold_met_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('upvote',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('hmac_token', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'hmac_token', name='uq_upvote_post_hmac')
    )
    op.create_table('petition_signature',
    sa.Column('petition_id', sa.Uuid(), nullable=False),
    sa.Column('hmac_token', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('petition_id', 'hmac_token', name='uq_sig_petition_hmac')
    )
    # ### end Alembic commands ###

    import uuid
    topic_table = sa.table('topic',
        sa.column('id', sa.Uuid()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String())
    )
    op.bulk_insert(
        topic_table,
        [
            {'id': uuid.uuid4(), 'name': 'Housing', 'description': 'Discussions about student housing'},
            {'id': uuid.uuid4(), 'name': 'Fees', 'description': 'Discussions about tuition and fees'},
            {'id': uuid.uuid4(), 'name': 'Lecturers', 'description': 'Discussions about lecturers and classes'},
            {'id': uuid.uuid4(), 'name': 'Admin', 'description': 'Discussions about university administration'},
            {'id': uuid.uuid4(), 'name': 'Safety', 'description': 'Discussions about campus safety'},
            {'id': uuid.uuid4(), 'name': 'Mental Health', 'description': 'Discussions about mental health support'},
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petition_signature')
    op.drop_table('upvote')
    op.drop_table('petition')
    op.drop_table('moderation_log')
    op.drop_table('flag')
    op.drop_table('post')
    op.drop_table('topic')
    op.drop_index('ix_session_token_hmac', table_name='session_token')
    op.drop_table('session_token')
    # ### end Alembic commands ###
