"""add_hmac_token_to_flag

Revision ID: 954d08693228
Revises: 8e6ac8e519f7
Create Date: 2026-05-24 11:22:07.885281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954d08693228'
down_revision: Union[str, None] = '8e6ac8e519f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flag', sa.Column('hmac_token', sa.String(length=64), server_default='', nullable=False))
    op.alter_column('flag', 'hmac_token', server_default=None)
    op.create_unique_constraint('uq_flag_post_hmac', 'flag', ['post_id', 'hmac_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_flag_post_hmac', 'flag', type_='unique')
    op.drop_column('flag', 'hmac_token')
    # ### end Alembic commands ###
